# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# If the above is successful then this will deploy to the compiled/transpiled code to hosting service using Github Pages

name: drinks-calculator Build and Deploy

on:
  # Initiate manually
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      version:
        description: 'The release version number'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        echo "Version: ${{ github.event.inputs.version }}" :
